name: Basics
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
#  test: ^1.16.8
  test: ^1.6.0
  

  #xml dependencies
dependencies:
  xml: ^3.6.1
  #test
  dependencies:
  #  test: ^1.9.4
  #  test: ^1.16.8